//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Итог собес.
    /// </summary>
    // *** Start programmer edit section *** (ИтогСобес CustomAttributes)

    // *** End programmer edit section *** (ИтогСобес CustomAttributes)
    public enum ИтогСобес
    {
        
        // *** Start programmer edit section *** (ИтогСобес.ПриглНаРаб CustomAttributes)

        // *** End programmer edit section *** (ИтогСобес.ПриглНаРаб CustomAttributes)
        [Caption("ПриглНаРаб")]
        ПриглНаРаб,
        
        // *** Start programmer edit section *** (ИтогСобес.ОтклонКандид CustomAttributes)

        // *** End programmer edit section *** (ИтогСобес.ОтклонКандид CustomAttributes)
        [Caption("ОтклонКандид")]
        ОтклонКандид,
        
        // *** Start programmer edit section *** (ИтогСобес.НаРассмотр CustomAttributes)

        // *** End programmer edit section *** (ИтогСобес.НаРассмотр CustomAttributes)
        [Caption("НаРассмотр")]
        НаРассмотр,
    }
}
