//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рег результ.
    /// </summary>
    // *** Start programmer edit section *** (РегРезульт CustomAttributes)

    // *** End programmer edit section *** (РегРезульт CustomAttributes)
    [AutoAltered()]
    [Caption("Рег результ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегРезультE", new string[] {
            "ДатРегРезСобес as \'Дат рег рез собес\'",
            "ИтогСобес as \'Итог собес\'",
            "ОценкаКандид as \'Оценка кандид\'",
            "КрКомИлиОбсРеш as \'Кр ком или обс реш\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИОСотруд as \'Ф и о сотруд\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "ПланирСобес as \'Планир собес\'",
            "ПланирСобес.ИметьПриСебе as \'Иметь при себе\'"}, Hidden=new string[] {
            "Сотрудники.ФИОСотруд",
            "Организация.Наименование",
            "ПланирСобес.ИметьПриСебе"})]
    [MasterViewDefineAttribute("РегРезультE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОСотруд")]
    [MasterViewDefineAttribute("РегРезультE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("РегРезультE", "ПланирСобес", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ИметьПриСебе")]
    [View("РегРезультL", new string[] {
            "ДатРегРезСобес as \'Дат рег рез собес\'",
            "ИтогСобес as \'Итог собес\'",
            "ОценкаКандид as \'Оценка кандид\'",
            "КрКомИлиОбсРеш as \'Кр ком или обс реш\'",
            "Сотрудники.ФИОСотруд as \'Ф и о сотруд\'",
            "Организация.Наименование as \'Наименование\'",
            "ПланирСобес.ИметьПриСебе as \'Иметь при себе\'"})]
    public class РегРезульт : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатРегРезСобес;
        
        private IIS.Proba9.ИтогСобес fИтогСобес;
        
        private int fОценкаКандид;
        
        private string fКрКомИлиОбсРеш;
        
        private IIS.Proba9.Сотрудники fСотрудники;
        
        private IIS.Proba9.Организация fОрганизация;
        
        private IIS.Proba9.ПланирСобес fПланирСобес;
        
        // *** Start programmer edit section *** (РегРезульт CustomMembers)

        // *** End programmer edit section *** (РегРезульт CustomMembers)

        
        /// <summary>
        /// ДатРегРезСобес.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес CustomAttributes)
        public virtual System.DateTime ДатРегРезСобес
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Get start)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Get start)
                System.DateTime result = this.fДатРегРезСобес;
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Get end)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Set start)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Set start)
                this.fДатРегРезСобес = value;
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Set end)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Set end)
            }
        }
        
        /// <summary>
        /// ИтогСобес.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ИтогСобес CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ИтогСобес CustomAttributes)
        public virtual IIS.Proba9.ИтогСобес ИтогСобес
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ИтогСобес Get start)

                // *** End programmer edit section *** (РегРезульт.ИтогСобес Get start)
                IIS.Proba9.ИтогСобес result = this.fИтогСобес;
                // *** Start programmer edit section *** (РегРезульт.ИтогСобес Get end)

                // *** End programmer edit section *** (РегРезульт.ИтогСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ИтогСобес Set start)

                // *** End programmer edit section *** (РегРезульт.ИтогСобес Set start)
                this.fИтогСобес = value;
                // *** Start programmer edit section *** (РегРезульт.ИтогСобес Set end)

                // *** End programmer edit section *** (РегРезульт.ИтогСобес Set end)
            }
        }
        
        /// <summary>
        /// КрКомИлиОбсРеш.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.КрКомИлиОбсРеш CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.КрКомИлиОбсРеш CustomAttributes)
        [StrLen(255)]
        public virtual string КрКомИлиОбсРеш
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.КрКомИлиОбсРеш Get start)

                // *** End programmer edit section *** (РегРезульт.КрКомИлиОбсРеш Get start)
                string result = this.fКрКомИлиОбсРеш;
                // *** Start programmer edit section *** (РегРезульт.КрКомИлиОбсРеш Get end)

                // *** End programmer edit section *** (РегРезульт.КрКомИлиОбсРеш Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.КрКомИлиОбсРеш Set start)

                // *** End programmer edit section *** (РегРезульт.КрКомИлиОбсРеш Set start)
                this.fКрКомИлиОбсРеш = value;
                // *** Start programmer edit section *** (РегРезульт.КрКомИлиОбсРеш Set end)

                // *** End programmer edit section *** (РегРезульт.КрКомИлиОбсРеш Set end)
            }
        }
        
        /// <summary>
        /// ОценкаКандид.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ОценкаКандид CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ОценкаКандид CustomAttributes)
        public virtual int ОценкаКандид
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ОценкаКандид Get start)

                // *** End programmer edit section *** (РегРезульт.ОценкаКандид Get start)
                int result = this.fОценкаКандид;
                // *** Start programmer edit section *** (РегРезульт.ОценкаКандид Get end)

                // *** End programmer edit section *** (РегРезульт.ОценкаКандид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ОценкаКандид Set start)

                // *** End programmer edit section *** (РегРезульт.ОценкаКандид Set start)
                this.fОценкаКандид = value;
                // *** Start programmer edit section *** (РегРезульт.ОценкаКандид Set end)

                // *** End programmer edit section *** (РегРезульт.ОценкаКандид Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.Организация CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Proba9.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.Организация Get start)

                // *** End programmer edit section *** (РегРезульт.Организация Get start)
                IIS.Proba9.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (РегРезульт.Организация Get end)

                // *** End programmer edit section *** (РегРезульт.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.Организация Set start)

                // *** End programmer edit section *** (РегРезульт.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (РегРезульт.Организация Set end)

                // *** End programmer edit section *** (РегРезульт.Организация Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ПланирСобес CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ПланирСобес CustomAttributes)
        [PropertyStorage(new string[] {
                "ПланирСобес"})]
        [NotNull()]
        public virtual IIS.Proba9.ПланирСобес ПланирСобес
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Get start)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Get start)
                IIS.Proba9.ПланирСобес result = this.fПланирСобес;
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Get end)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Set start)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Set start)
                this.fПланирСобес = value;
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Set end)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proba9.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.Сотрудники Get start)

                // *** End programmer edit section *** (РегРезульт.Сотрудники Get start)
                IIS.Proba9.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (РегРезульт.Сотрудники Get end)

                // *** End programmer edit section *** (РегРезульт.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.Сотрудники Set start)

                // *** End programmer edit section *** (РегРезульт.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (РегРезульт.Сотрудники Set end)

                // *** End programmer edit section *** (РегРезульт.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегРезультE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегРезультE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегРезультE", typeof(IIS.Proba9.РегРезульт));
                }
            }
            
            /// <summary>
            /// "РегРезультL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегРезультL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегРезультL", typeof(IIS.Proba9.РегРезульт));
                }
            }
        }
    }
}
