//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧПланирСобес.
    /// </summary>
    // *** Start programmer edit section *** (ТЧПланирСобес CustomAttributes)

    // *** End programmer edit section *** (ТЧПланирСобес CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧПланирСобесE", new string[] {
            "ТЧРегистАнкеты",
            "ТЧРегистАнкеты.ИНН",
            "ТЧРегистАнкеты.НомерТелефона",
            "ТЧРегистАнкеты.СерНомПаспорта",
            "ТЧРегистАнкеты.Снилс",
            "ТЧРегистАнкеты.ФИОКандидата",
            "ТЧРегистАнкеты.ЭлПочта",
            "ТЧРегистАнкеты.Должности.Должности"})]
    public class ТЧПланирСобес : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Proba9.ТЧРегистАнкеты fТЧРегистАнкеты;
        
        private IIS.Proba9.ПланирСобес fПланирСобес;
        
        // *** Start programmer edit section *** (ТЧПланирСобес CustomMembers)

        // *** End programmer edit section *** (ТЧПланирСобес CustomMembers)

        
        /// <summary>
        /// ТЧПланирСобес.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты CustomAttributes)

        // *** End programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты CustomAttributes)
        [PropertyStorage(new string[] {
                "ТЧРегистАнкеты"})]
        [NotNull()]
        public virtual IIS.Proba9.ТЧРегистАнкеты ТЧРегистАнкеты
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты Get start)

                // *** End programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты Get start)
                IIS.Proba9.ТЧРегистАнкеты result = this.fТЧРегистАнкеты;
                // *** Start programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты Get end)

                // *** End programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты Set start)

                // *** End programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты Set start)
                this.fТЧРегистАнкеты = value;
                // *** Start programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты Set end)

                // *** End programmer edit section *** (ТЧПланирСобес.ТЧРегистАнкеты Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proba9.ПланирСобес.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПланирСобес.ПланирСобес CustomAttributes)

        // *** End programmer edit section *** (ТЧПланирСобес.ПланирСобес CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПланирСобес"})]
        public virtual IIS.Proba9.ПланирСобес ПланирСобес
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПланирСобес.ПланирСобес Get start)

                // *** End programmer edit section *** (ТЧПланирСобес.ПланирСобес Get start)
                IIS.Proba9.ПланирСобес result = this.fПланирСобес;
                // *** Start programmer edit section *** (ТЧПланирСобес.ПланирСобес Get end)

                // *** End programmer edit section *** (ТЧПланирСобес.ПланирСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПланирСобес.ПланирСобес Set start)

                // *** End programmer edit section *** (ТЧПланирСобес.ПланирСобес Set start)
                this.fПланирСобес = value;
                // *** Start programmer edit section *** (ТЧПланирСобес.ПланирСобес Set end)

                // *** End programmer edit section *** (ТЧПланирСобес.ПланирСобес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧПланирСобесE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧПланирСобесE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧПланирСобесE", typeof(IIS.Proba9.ТЧПланирСобес));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧПланирСобес.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧПланирСобес CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧПланирСобес CustomAttributes)
    public class DetailArrayOfТЧПланирСобес : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proba9.DetailArrayOfТЧПланирСобес members)

        // *** End programmer edit section *** (IIS.Proba9.DetailArrayOfТЧПланирСобес members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧПланирСобес by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧПланирСобес.
        /// </summary>
        public DetailArrayOfТЧПланирСобес(IIS.Proba9.ПланирСобес fПланирСобес) : 
                base(typeof(ТЧПланирСобес), ((ICSSoft.STORMNET.DataObject)(fПланирСобес)))
        {
        }
        
        public IIS.Proba9.ТЧПланирСобес this[int index]
        {
            get
            {
                return ((IIS.Proba9.ТЧПланирСобес)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proba9.ТЧПланирСобес dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
